services:

  postgres:
    image: postgres:16
    container_name: freelance-hub-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: freelance_hub
      POSTGRES_USER: Sparsh78.in
      POSTGRES_PASSWORD: Sp#2547Ugko*75
      TZ: Asia/Kolkata,
      PGTZ: Asia/Kolkata

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: