spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/freelance_hub?options=-c%20TimeZone=Asia%2FKolkata
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

server:
  port: 8081