spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/freelance_hub?options=-c%20TimeZone=UTC
    username: freelance_hub
    password: freelance_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL16Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true

  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: false

jwt:
  secret: dev-only-insecure-secret-change-me-32-bytes-minimum
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

logging:
  level:
    com.sparsh.freelancehub: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8081
