spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/freelance_hub?options=-c%20TimeZone=Asia%2FKolkata
    username: ${POSTGRES_USER:freelance_hub}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true

    show-sql: true

server:
  port: 8081